name: medico
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.13.0
  google_fonts: ^5.1.0
  animated_bottom_navigation_bar: ^1.2.0
  carousel_slider: ^4.2.1
  http: ^1.1.0
  get: ^4.6.6
  dio: ^5.3.3
  flutter_secure_storage: ^9.0.0
  loading_animation_widget: ^1.2.0+4
  json_annotation: ^4.8.1
  image_picker: ^1.0.4
  overlay_loader_with_app_icon: ^0.0.3
  flutter_screenutil: ^5.9.0
  device_preview: ^1.1.0
  lottie: ^2.7.0
  flutter_circular_text: ^0.3.1
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  intl: ^0.18.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  internet_connection_checker: ^1.0.0+1
  firebase_messaging: ^14.7.9
  file_picker: ^6.1.1
  archive: ^3.4.10
  syncfusion_flutter_pdfviewer: ^24.1.45
  open_file: ^3.3.2
  flutter_local_notifications: ^16.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
